
package Interfaz;

import Model.Evento;
import Model.Usuario;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elise
 */
public class EstudianteProfesor extends javax.swing.JFrame {
    
        private static final String DIRECTORIO_EVENTOS = "C:/Users/elise/OneDrive/Desktop/reservas/";
         

    /**
     * Creates new form EstudianteProfesor
     */
    public EstudianteProfesor() {
        initComponents();
        setLocationRelativeTo(null);
       
    // Inicializar la tabla vacía
     
    limpiarTabla();
    cargarEventosDesdeArchivo();
    
    }
    
    public void cargarEventosDesdeArchivo(){
        File directorio = new File(DIRECTORIO_EVENTOS);
        if (!directorio.exists()){
            directorio.mkdirs();
            return;
        }
        
        File[] archivos = directorio.listFiles((dir, name) -> name.endsWith(".txt"));
        if (archivos == null) return;
        
        DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
        model.setRowCount(0); //limpia la tabla
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        for(File archivo : archivos){
            try (BufferedReader leer = new BufferedReader(new FileReader(archivo))) {
              String line;
              String nombreEvento = "";
              String fechaInicio = "";
              String descripcion = "";
              String fechaCreada = "";
              String estado = "Pendiente";
              
              while ((line = leer.readLine()) != null) {
                if (line.startsWith("NOMBRE_EVENTO: ")) {
                    nombreEvento = line.substring("NOMBRE_EVENTO: ".length());
                    
                } else if (line.startsWith("DESCRIPCION: ")){
                    descripcion = line.substring("DESCRIPCION: ".length());
                    
                } else if (line.startsWith("FECHA_INICIO: ")) {
                    fechaInicio = line.substring("FECHA_INICIO: ".length());
                    
                } else if (line.startsWith("FECHA_CREADA: ")){
                     fechaCreada = line.substring("FECHA_CREADA".length());
                } else if (line.startsWith("ESTADO: ")) {
                    estado = line.substring("ESTADO: ".length());
                }
            }
              if(!nombreEvento.isEmpty()){
                  model.addRow(new Object[]{
                      fechaInicio,
                      nombreEvento,
                      descripcion,
                      estado,
                      //evento pendiente
                      
                      fechaCreada
                  });
              }
            } catch (IOException e){
                JOptionPane.showMessageDialog(null,"Error al leer archivo" +e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                
            }
           

        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        txtEvento = new javax.swing.JTextField();
        btnAgregarEvento = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        dateINICIO = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModelSolicitudes = new javax.swing.JTable();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("AGREGAR"));

        txtEvento.setBorder(javax.swing.BorderFactory.createTitledBorder("EVENTO"));
        txtEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventoActionPerformed(evt);
            }
        });

        btnAgregarEvento.setText("AGREGAR");
        btnAgregarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEventoActionPerformed(evt);
            }
        });

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("FECHA INICIO");

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCRIPCION"));
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnAgregarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(dateINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addComponent(txtEvento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEvento)
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar.getContentPane());
        Agregar.getContentPane().setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SISTEMA DE SOLICITUD"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("ACTUALIZAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ModelSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FECHA DE INICIO", "EVENTO", "DESCRIPCION", "ESTADO", "CREADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ModelSolicitudes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventoActionPerformed

    private void btnAgregarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEventoActionPerformed
         
        agregarATabla(); 
        agregarAArchivo();
        limpiarCampos();

        Agregar.dispose();
        
    }//GEN-LAST:event_btnAgregarEventoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Agregar.dispose();
   
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      
      Agregar.setVisible(true);
      Agregar.setSize(400,440);
      Agregar.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       int selectedRow = ModelSolicitudes.getSelectedRow();
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    // guarda el nombre del evento 
    final String nombreEventoOrigianl = ModelSolicitudes.getValueAt(selectedRow, 1).toString();
    
    
    // Mostrar diálogo de edición con los datos actuales
    Agregar.setVisible(true);
    Agregar.setSize(365, 410);
    Agregar.setLocationRelativeTo(null);
    
    // Llenar campos con datos existentes
    txtEvento.setText(ModelSolicitudes.getValueAt(selectedRow, 1).toString());
    txtDescripcion.setText(ModelSolicitudes.getValueAt(selectedRow, 2).toString());
    
    // Configurar botón para actualizar en lugar de agregar
    btnAgregarEvento.setText("ACTUALIZAR");
    btnAgregarEvento.removeActionListener(btnAgregarEvento.getActionListeners()[0]);
    btnAgregarEvento.addActionListener(e -> {
        
        String nombreArchivoOriginal = DIRECTORIO_EVENTOS + nombreEventoOrigianl.replaceAll("[^a-zA-Z0-9]", 
                "_")+ ".txt";
              File archivoOriginal = new File(nombreArchivoOriginal);
              if (archivoOriginal.exists()){
                  archivoOriginal.delete();
              }
            
            actualizarFila(selectedRow);
            agregarAArchivo();
            limpiarCampos();
            Agregar.dispose();
        
    });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
    int selectedRow = ModelSolicitudes.getSelectedRow();
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    //obtener el nombre del evento para eliminar el archivo
    
    String nombreEvento = ModelSolicitudes.getValueAt(selectedRow, 1).toString();
    String nombreArchivo = DIRECTORIO_EVENTOS + nombreEvento.replaceAll("[^a-zA-Z0-9]", "_")+ ".txt";
    
    //elimina archivo
    File archivo = new File(nombreArchivo);
    if(archivo.exists()) {
        archivo.delete();
    }
    
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
    model.removeRow(selectedRow);
                                        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar;
    private javax.swing.JTable ModelSolicitudes;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarEvento;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser dateINICIO;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

private void actualizarFila(int row) {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format(dateINICIO.getDate());
    String tomestamp = sdf.format(new Date());
    
    ModelSolicitudes.setValueAt(fechaInicioStr, row, 0);
    ModelSolicitudes.setValueAt(txtEvento.getText(), row, 1);
    ModelSolicitudes.setValueAt(txtDescripcion.getText(), row, 2);
    ModelSolicitudes.setValueAt(tomestamp, row, 4); //actualiza fecha modificacion
    
    // Restaurar botón a su estado original
    btnAgregarEvento.setText("AGREGAR");
    btnAgregarEvento.removeActionListener(btnAgregarEvento.getActionListeners()[0]);
    btnAgregarEvento.addActionListener(this::btnAgregarEventoActionPerformed);
}
public void agregarATabla() {
    Evento evento = new Evento();
    evento.setDescripcion(txtDescripcion.getText());
    evento.setFechaInicio(dateINICIO.getDate());
    evento.setNombreEvento(txtEvento.getText());
    
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format(evento.getFechaInicio());
    String timestamp = sdf.format(new Date());
    evento.setFechaCreada(timestamp);
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
    model.addRow(new Object[]{
        fechaInicioStr, 
        evento.getNombreEvento(), 
        evento.getDescripcion(), 
        evento.getEstado(),
        
        timestamp
            
    });
}
private void limpiarCampos() {
    txtEvento.setText("");
    txtDescripcion.setText("");
    dateINICIO.setDate(null);
    txtNombre.setText("");
}
private void limpiarTabla() {
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
    model.setRowCount(0); 
}

    private void agregarAArchivo() {
    String nombreEvento = txtEvento.getText();
    Date fechaInicio = dateINICIO.getDate();
    String descripcion = txtDescripcion.getText();
    String nombreUsuario = txtNombre.getText();
    
    if(nombreEvento.isEmpty() || fechaInicio == null || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Evento evento = new Evento();
    evento.setNombreEvento(nombreEvento);
    evento.setFechaInicio(fechaInicio);
    evento.setDescripcion(descripcion);
    evento.setNombreuUsuario(nombreUsuario);
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    evento.setFechaCreada(sdf.format(new Date()));
    
    String nombreArchivo = DIRECTORIO_EVENTOS + 
                         nombreEvento.replaceAll("[^a-zA-Z0-9]", "_") + 
                         ".txt";
    
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo))) {
        writer.write("==========DATOS DEL EVENTO==========\n"); 
        writer.write("NOMBRE_EVENTO: " + evento.getNombreEvento() + "\n");
        writer.write("FECHA_INICIO: " + sdf.format(evento.getFechaInicio()) + "\n");
        writer.write("FECHA_CREADA: " + evento.getFechaCreada() + "\n");
        writer.write("DESCRIPCION: " + evento.getDescripcion() + "\n");
        writer.write("ESTADO: " + evento.getEstado()+"\n");
        writer.write("NOMBRE_USUARIO: " + evento.getNombreuUsuario());
        
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, 
            "Error al crear el archivo: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        System.err.println("Error al registrar evento: " + e.getMessage());
    }
}
}