
package Interfaz;

import Model.Evento;
import Model.Usuario;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import validaciones.*;

/**
 *
 * @author elise
 */
public class EstudianteProfesor extends javax.swing.JFrame {
    
        private static final String DIRECTORIO_EVENTOS = "C:/Users/elise/OneDrive/Desktop/reservas/";
         

    /**
     * Creates new form EstudianteProfesor
     */
    public EstudianteProfesor() {
        initComponents();
        setLocationRelativeTo(null);
       
    
       setResizable(false);
    limpiarTabla();
    cargarEventosDesdeArchivo();
    
    }
    
    public void cargarEventosDesdeArchivo(){
        File directorio = new File(DIRECTORIO_EVENTOS);
        if (!directorio.exists()){
            directorio.mkdirs();
            return;
        }
        
        File[] archivos = directorio.listFiles((dir, name) -> name.endsWith(".txt"));
        if (archivos == null) return;
        
        DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
        model.setRowCount(0); //limpia la tabla
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        for(File archivo : archivos){
            try (BufferedReader leer = new BufferedReader(new FileReader(archivo))) {
              String line;
              String nombreEvento = "";
              String fechaInicio = "";
              String descripcion = "";
              String fechaCreada = "";
              String estado = "Pendiente";
              
              while ((line = leer.readLine()) != null) {
                if (line.startsWith("NOMBRE_EVENTO: ")) {
                    nombreEvento = line.substring("NOMBRE_EVENTO: ".length());
                    
                } else if (line.startsWith("DESCRIPCION: ")){
                    descripcion = line.substring("DESCRIPCION: ".length());
                    
                } else if (line.startsWith("FECHA_INICIO: ")) {
                    fechaInicio = line.substring("FECHA_INICIO: ".length());
                    
                } else if (line.startsWith("FECHA_CREADA: ")){
                     fechaCreada = line.substring("FECHA_CREADA".length());
                } else if (line.startsWith("ESTADO: ")) {
                    estado = line.substring("ESTADO: ".length());
                }
            }
              if(!nombreEvento.isEmpty()){
                  model.addRow(new Object[]{
                      fechaInicio,
                      nombreEvento,
                      descripcion,
                      estado,
                      
                      
                      fechaCreada
                  });
              }
            } catch (IOException e){
                JOptionPane.showMessageDialog(null,"Error al leer archivo" +e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                
            }
           

        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        txtEvento = new javax.swing.JTextField();
        btnAgregarEvento = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        dateINICIO = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEliminarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnActualizarPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModelSolicitudes = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGREGAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        txtEvento.setBorder(javax.swing.BorderFactory.createTitledBorder("EVENTO"));
        txtEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventoActionPerformed(evt);
            }
        });

        btnAgregarEvento.setBackground(new java.awt.Color(51, 51, 255));
        btnAgregarEvento.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnAgregarEvento.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarEvento.setText("AGREGAR");
        btnAgregarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEventoActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(51, 51, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FECHA INICIO");

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCRIPCION"));
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAgregarEvento)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(dateINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addComponent(txtEvento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEvento)
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar.getContentPane());
        Agregar.getContentPane().setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SISTEMA DE SOLICITUD"));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ChatGPT Image 23 may 2025, 01_40_18 a.m. (1) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnPanel.setBackground(new java.awt.Color(51, 51, 255));
        btnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("AGREGAR");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar (1).png"))); // NOI18N

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEliminarPanel.setBackground(new java.awt.Color(51, 51, 255));
        btnEliminarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarPanelMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ELIMINAR");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N

        javax.swing.GroupLayout btnEliminarPanelLayout = new javax.swing.GroupLayout(btnEliminarPanel);
        btnEliminarPanel.setLayout(btnEliminarPanelLayout);
        btnEliminarPanelLayout.setHorizontalGroup(
            btnEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28))))
        );
        btnEliminarPanelLayout.setVerticalGroup(
            btnEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnActualizarPanel.setBackground(new java.awt.Color(51, 51, 255));
        btnActualizarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarPanelMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ACTUALIZAR");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar (1).jpg"))); // NOI18N

        javax.swing.GroupLayout btnActualizarPanelLayout = new javax.swing.GroupLayout(btnActualizarPanel);
        btnActualizarPanel.setLayout(btnActualizarPanelLayout);
        btnActualizarPanelLayout.setHorizontalGroup(
            btnActualizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnActualizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btnActualizarPanelLayout.setVerticalGroup(
            btnActualizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("INICIO");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/inico (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnActualizarPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        ModelSolicitudes.setBackground(new java.awt.Color(204, 204, 204));
        ModelSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FECHA DE INICIO", "EVENTO", "DESCRIPCION", "ESTADO", "CREADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ModelSolicitudes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventoActionPerformed

    private void btnAgregarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEventoActionPerformed
         
        agregarATabla(); 
        agregarAArchivo();
        limpiarCampos();
          
        Agregar.dispose();
        
    }//GEN-LAST:event_btnAgregarEventoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Agregar.dispose();
   
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelMouseClicked
        // TODO add your handling code here:
         Agregar.setVisible(true);
         Agregar.setSize(400,440);
         Agregar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnPanelMouseClicked

    private void btnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelMouseEntered
        // TODO add your handling code here:normal=[0,0,51],5  al pasar mause=0,51,209
        Border bordeNormal = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),2);
        btnPanel.setBorder(bordeNormal);
        btnPanel.setBackground(new java.awt.Color(0,51,209));
           
    }//GEN-LAST:event_btnPanelMouseEntered

    private void btnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelMouseExited
        // TODO add your handling code here:
       Border borde = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
       btnPanel.setBorder(borde);
       btnPanel.setBackground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_btnPanelMouseExited

    private void btnEliminarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPanelMouseClicked
        // TODO add your handling code here:
        eliminarEvento();
        
        
    }//GEN-LAST:event_btnEliminarPanelMouseClicked

    private void btnEliminarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPanelMouseEntered
        // TODO add your handling code here:normal=[0,0,51],5  al pasar mause=0,51,209
        Border bordeNormal = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),2);
        btnEliminarPanel.setBorder(bordeNormal);
        btnEliminarPanel.setBackground(new java.awt.Color(0,51,209));
        
    }//GEN-LAST:event_btnEliminarPanelMouseEntered

    private void btnEliminarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPanelMouseExited
        // TODO add your handling code here:
        Border borde = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnEliminarPanel.setBorder(borde);
        btnEliminarPanel.setBackground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_btnEliminarPanelMouseExited

    private void btnActualizarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPanelMouseClicked
        // TODO add your handling code here:
        actualizarArchivo();
    }//GEN-LAST:event_btnActualizarPanelMouseClicked

    private void btnActualizarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPanelMouseEntered
        // TODO add your handling code here:normal=[0,0,51],5  al pasar mause=0,51,209
        Border bordeNormal = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),2);
        btnActualizarPanel.setBorder(bordeNormal);
        btnActualizarPanel.setBackground(new java.awt.Color(0,51,209));
    }//GEN-LAST:event_btnActualizarPanelMouseEntered

    private void btnActualizarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPanelMouseExited
        // TODO add your handling code here:
        Border borde = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnActualizarPanel.setBorder(borde);
        btnActualizarPanel.setBackground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_btnActualizarPanelMouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
         Login L = new Login();
        L.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        Border p = BorderFactory.createLineBorder(Color.white);
        jPanel3.setBorder(p);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        Border o = BorderFactory.createLineBorder(null);
        jPanel3.setBorder(o);
    }//GEN-LAST:event_jPanel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar;
    private javax.swing.JTable ModelSolicitudes;
    private javax.swing.JPanel btnActualizarPanel;
    private javax.swing.JButton btnAgregarEvento;
    private javax.swing.JPanel btnEliminarPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser dateINICIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

private void actualizarFila(int row) {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format(dateINICIO.getDate());
    String tomestamp = sdf.format(new Date());
    
    ModelSolicitudes.setValueAt(fechaInicioStr, row, 0);
    ModelSolicitudes.setValueAt(txtEvento.getText(), row, 1);
    ModelSolicitudes.setValueAt(txtDescripcion.getText(), row, 2);
    ModelSolicitudes.setValueAt(tomestamp, row, 4); 
    
    
    btnAgregarEvento.setText("AGREGAR");
    btnAgregarEvento.removeActionListener(btnAgregarEvento.getActionListeners()[0]);
    btnAgregarEvento.addActionListener(this::btnAgregarEventoActionPerformed);
}
  public void agregarATabla() {
    Evento evento = new Evento();
    evento.setDescripcion(txtDescripcion.getText());
    evento.setFechaInicio(dateINICIO.getDate());
    evento.setNombreEvento(txtEvento.getText());
    
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format(evento.getFechaInicio());
    String timestamp = sdf.format(new Date());
    evento.setFechaCreada(timestamp);
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
    model.addRow(new Object[]{
        fechaInicioStr, 
        evento.getNombreEvento(), 
        evento.getDescripcion(), 
        evento.getEstado(),
        
        timestamp
            
    });
}
private void limpiarCampos() {
    txtEvento.setText("");
    txtDescripcion.setText("");
    dateINICIO.setDate(null);
    txtNombre.setText("");
}
private void limpiarTabla() {
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
    model.setRowCount(0); 
}

    private void agregarAArchivo() {
    String nombreEvento = txtEvento.getText();
    Date fechaInicio = dateINICIO.getDate();
    String descripcion = txtDescripcion.getText();
    String nombreUsuario = txtNombre.getText();
    
    if(nombreEvento.isEmpty() || fechaInicio == null || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Evento evento = new Evento();
    evento.setNombreEvento(nombreEvento);
    evento.setFechaInicio(fechaInicio);
    evento.setDescripcion(descripcion);
    evento.setNombreuUsuario(nombreUsuario);
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    evento.setFechaCreada(sdf.format(new Date()));
    
    String nombreArchivo = DIRECTORIO_EVENTOS + 
                         nombreEvento.replaceAll("[^a-zA-Z0-9]", "") + 
                         ".txt";
    
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo))) {
        writer.write("==========DATOS DEL EVENTO==========\n"); 
        writer.write("NOMBRE_EVENTO: " + evento.getNombreEvento() + "\n");
        writer.write("FECHA_INICIO: " + sdf.format(evento.getFechaInicio()) + "\n");
        writer.write("FECHA_CREADA: " + evento.getFechaCreada() + "\n");
        writer.write("DESCRIPCION: " + evento.getDescripcion() + "\n");
        writer.write("ESTADO: " + evento.getEstado()+"\n");
        writer.write("NOMBRE_USUARIO: " + evento.getNombreuUsuario());
        
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, 
            "Error al crear el archivo: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        System.err.println("Error al registrar evento: " + e.getMessage());
    }
}
    
    private void actualizarArchivo(){
         int selectedRow = ModelSolicitudes.getSelectedRow();
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
     
    final String nombreEventoOrigianl = ModelSolicitudes.getValueAt(selectedRow, 1).toString();
    
    
   
    Agregar.setVisible(true);
    Agregar.setSize(365, 450);
    Agregar.setLocationRelativeTo(null);
    
    
    txtEvento.setText(ModelSolicitudes.getValueAt(selectedRow, 1).toString());
    txtDescripcion.setText(ModelSolicitudes.getValueAt(selectedRow, 2).toString());
    
    
    btnAgregarEvento.setText("ACTUALIZAR");
    btnAgregarEvento.removeActionListener(btnAgregarEvento.getActionListeners()[0]);
    btnAgregarEvento.addActionListener(e -> {
        
        String nombreArchivoOriginal = DIRECTORIO_EVENTOS + nombreEventoOrigianl.replaceAll("[^a-zA-Z0-9]", 
                "")+ ".txt";
              File archivoOriginal = new File(nombreArchivoOriginal);
              if (archivoOriginal.exists()){
                  archivoOriginal.delete();
              }
            
            actualizarFila(selectedRow);
            agregarAArchivo();
            limpiarCampos();
            Agregar.dispose();
        
    });
    }
    
    private void eliminarEvento(){
         int selectedRow = ModelSolicitudes.getSelectedRow();
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    
    
    String nombreEvento = ModelSolicitudes.getValueAt(selectedRow, 1).toString();
    String nombreArchivo = DIRECTORIO_EVENTOS + nombreEvento.replaceAll("[^a-zA-Z0-9]", "")+ ".txt";
    
   
    File archivo = new File(nombreArchivo);
    if(archivo.exists()) {
        archivo.delete();
    }
    
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes.getModel();
    model.removeRow(selectedRow);
    }
}