/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import DAO.*;
import Model.*;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {
RegistroDAO registro= new RegistroDAO();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         setResizable(false);
         setLocationRelativeTo(null);
         Registro.setLocationRelativeTo(login);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        btnAtrasPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Estudiante = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtApellidoestudiante = new javax.swing.JTextField();
        txtFacultadestudiante = new javax.swing.JTextField();
        txtGmailestudiante = new javax.swing.JTextField();
        txtProgramaestudiante = new javax.swing.JTextField();
        txtCelularestudiante = new javax.swing.JTextField();
        txtNombreestudiante = new javax.swing.JTextField();
        txtIDestudiante = new javax.swing.JTextField();
        txtSemestreestudiante = new javax.swing.JTextField();
        comboboxGeneroEstudiantee = new javax.swing.JComboBox<>();
        btnPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Profesor = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        txtApellidoprofesor = new javax.swing.JTextField();
        txtFacultadprofesor = new javax.swing.JTextField();
        txtProgramaprofesor = new javax.swing.JTextField();
        txtNombreprofesor = new javax.swing.JTextField();
        txtProfesionprofesor = new javax.swing.JTextField();
        txtGmailprofesor = new javax.swing.JTextField();
        txtCelularprofesor = new javax.swing.JTextField();
        txtIDprofesor = new javax.swing.JTextField();
        comboBoxGeneroProfesor = new javax.swing.JComboBox<>();
        btnPanelRegistrar5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPanelRegresar4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BienestarDialogo = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        txtNombrebienestar = new javax.swing.JTextField();
        txtIDbienestar = new javax.swing.JTextField();
        txtApellidobienestar = new javax.swing.JTextField();
        txtOficionbienestar = new javax.swing.JTextField();
        txtDepartamentobienestar = new javax.swing.JTextField();
        txtGmailbienestar = new javax.swing.JTextField();
        txtDireccionbienestar = new javax.swing.JTextField();
        txtCelularbienestar = new javax.swing.JTextField();
        comoboBoxGeneroBienestar = new javax.swing.JComboBox<>();
        BTNregistrar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnREGRESAR = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        txtIDLogin = new javax.swing.JTextField();
        txtGmailLogin = new javax.swing.JTextField();
        btnIniciarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        comboTipoUsuario.setBackground(new java.awt.Color(51, 51, 255));
        comboTipoUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        comboTipoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        comboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar", "estudiante", "profesor", "bienestar" }));
        comboTipoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        comboTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoUsuarioActionPerformed(evt);
            }
        });

        btnAtrasPanel.setBackground(new java.awt.Color(51, 51, 255));
        btnAtrasPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasPanelMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ATRAS");

        javax.swing.GroupLayout btnAtrasPanelLayout = new javax.swing.GroupLayout(btnAtrasPanel);
        btnAtrasPanel.setLayout(btnAtrasPanelLayout);
        btnAtrasPanelLayout.setHorizontalGroup(
            btnAtrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAtrasPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btnAtrasPanelLayout.setVerticalGroup(
            btnAtrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAtrasPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(comboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnAtrasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtrasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro.getContentPane());
        Registro.getContentPane().setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTUDIANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        txtApellidoestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));

        txtFacultadestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("FACULTAD"));
        txtFacultadestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacultadestudianteActionPerformed(evt);
            }
        });

        txtGmailestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("GMAIL"));

        txtProgramaestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("PROGRAMA"));

        txtCelularestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("CELULAR"));
        txtCelularestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularestudianteActionPerformed(evt);
            }
        });

        txtNombreestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));

        txtIDestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        txtSemestreestudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("SEMESTRE"));
        txtSemestreestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemestreestudianteActionPerformed(evt);
            }
        });

        comboboxGeneroEstudiantee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer", "otro" }));
        comboboxGeneroEstudiantee.setBorder(javax.swing.BorderFactory.createTitledBorder("GENERO"));

        btnPanel2.setBackground(new java.awt.Color(51, 51, 255));
        btnPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanel2MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("REGISTRAR");

        javax.swing.GroupLayout btnPanel2Layout = new javax.swing.GroupLayout(btnPanel2);
        btnPanel2.setLayout(btnPanel2Layout);
        btnPanel2Layout.setHorizontalGroup(
            btnPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btnPanel2Layout.setVerticalGroup(
            btnPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPanel1.setBackground(new java.awt.Color(51, 51, 255));
        btnPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanel1MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("REGRESAR");

        javax.swing.GroupLayout btnPanel1Layout = new javax.swing.GroupLayout(btnPanel1);
        btnPanel1.setLayout(btnPanel1Layout);
        btnPanel1Layout.setHorizontalGroup(
            btnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        btnPanel1Layout.setVerticalGroup(
            btnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIDestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGmailestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxGeneroEstudiantee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtProgramaestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSemestreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFacultadestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtNombreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelularestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btnPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGmailestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIDestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboboxGeneroEstudiantee, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelularestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProgramaestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFacultadestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSemestreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout EstudianteLayout = new javax.swing.GroupLayout(Estudiante.getContentPane());
        Estudiante.getContentPane().setLayout(EstudianteLayout);
        EstudianteLayout.setHorizontalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EstudianteLayout.setVerticalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROFESOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        txtApellidoprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));

        txtFacultadprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("FACULTAD"));

        txtProgramaprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("PROGRAMA"));

        txtNombreprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));

        txtProfesionprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("PROFESION"));

        txtGmailprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("GMAIL"));

        txtCelularprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("CELULAR"));
        txtCelularprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularprofesorActionPerformed(evt);
            }
        });

        txtIDprofesor.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        comboBoxGeneroProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer", "otro" }));
        comboBoxGeneroProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder("GENERO"));
        comboBoxGeneroProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGeneroProfesorActionPerformed(evt);
            }
        });

        btnPanelRegistrar5.setBackground(new java.awt.Color(51, 51, 255));
        btnPanelRegistrar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanelRegistrar5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanelRegistrar5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanelRegistrar5MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("REGISTRAR");

        javax.swing.GroupLayout btnPanelRegistrar5Layout = new javax.swing.GroupLayout(btnPanelRegistrar5);
        btnPanelRegistrar5.setLayout(btnPanelRegistrar5Layout);
        btnPanelRegistrar5Layout.setHorizontalGroup(
            btnPanelRegistrar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelRegistrar5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(23, 23, 23))
        );
        btnPanelRegistrar5Layout.setVerticalGroup(
            btnPanelRegistrar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelRegistrar5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        btnPanelRegresar4.setBackground(new java.awt.Color(51, 51, 255));
        btnPanelRegresar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanelRegresar4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanelRegresar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanelRegresar4MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("REGRESAR");

        javax.swing.GroupLayout btnPanelRegresar4Layout = new javax.swing.GroupLayout(btnPanelRegresar4);
        btnPanelRegresar4.setLayout(btnPanelRegresar4Layout);
        btnPanelRegresar4Layout.setHorizontalGroup(
            btnPanelRegresar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelRegresar4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(17, 17, 17))
        );
        btnPanelRegresar4Layout.setVerticalGroup(
            btnPanelRegresar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelRegresar4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtIDprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGmailprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxGeneroProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtNombreprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelularprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtProgramaprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFacultadprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProfesionprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(btnPanelRegistrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPanelRegresar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGmailprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIDprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxGeneroProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelularprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProgramaprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFacultadprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfesionprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPanelRegistrar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanelRegresar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout ProfesorLayout = new javax.swing.GroupLayout(Profesor.getContentPane());
        Profesor.getContentPane().setLayout(ProfesorLayout);
        ProfesorLayout.setHorizontalGroup(
            ProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ProfesorLayout.setVerticalGroup(
            ProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("BIENESTAR"));

        txtNombrebienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));

        txtIDbienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        txtApellidobienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));

        txtOficionbienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("OFICIO"));
        txtOficionbienestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOficionbienestarActionPerformed(evt);
            }
        });

        txtDepartamentobienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("DEPARTAMENTO"));
        txtDepartamentobienestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentobienestarActionPerformed(evt);
            }
        });

        txtGmailbienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("GMAIL"));

        txtDireccionbienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("DIRECCION"));

        txtCelularbienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("CELULAR"));
        txtCelularbienestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularbienestarActionPerformed(evt);
            }
        });

        comoboBoxGeneroBienestar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer", "otro" }));
        comoboBoxGeneroBienestar.setBorder(javax.swing.BorderFactory.createTitledBorder("GENERO"));
        comoboBoxGeneroBienestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoboBoxGeneroBienestarActionPerformed(evt);
            }
        });

        BTNregistrar.setBackground(new java.awt.Color(51, 51, 255));
        BTNregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNregistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNregistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNregistrarMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("REGISTRAR");

        javax.swing.GroupLayout BTNregistrarLayout = new javax.swing.GroupLayout(BTNregistrar);
        BTNregistrar.setLayout(BTNregistrarLayout);
        BTNregistrarLayout.setHorizontalGroup(
            BTNregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNregistrarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        BTNregistrarLayout.setVerticalGroup(
            BTNregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNregistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnREGRESAR.setBackground(new java.awt.Color(51, 51, 255));
        btnREGRESAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnREGRESARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnREGRESARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnREGRESARMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("REGRESAR");

        javax.swing.GroupLayout btnREGRESARLayout = new javax.swing.GroupLayout(btnREGRESAR);
        btnREGRESAR.setLayout(btnREGRESARLayout);
        btnREGRESARLayout.setHorizontalGroup(
            btnREGRESARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnREGRESARLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btnREGRESARLayout.setVerticalGroup(
            btnREGRESARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnREGRESARLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtIDbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGmailbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comoboBoxGeneroBienestar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtNombrebienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidobienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelularbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtDireccionbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOficionbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepartamentobienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(BTNregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnREGRESAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGmailbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIDbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comoboBoxGeneroBienestar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrebienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidobienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelularbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartamentobienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOficionbienestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnREGRESAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BienestarDialogoLayout = new javax.swing.GroupLayout(BienestarDialogo.getContentPane());
        BienestarDialogo.getContentPane().setLayout(BienestarDialogoLayout);
        BienestarDialogoLayout.setHorizontalGroup(
            BienestarDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BienestarDialogoLayout.setVerticalGroup(
            BienestarDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login.setBackground(new java.awt.Color(102, 204, 255));
        login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SISTEMA DE SOLICITUD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        txtIDLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        txtGmailLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("GMAIL:"));

        btnIniciarPanel.setBackground(new java.awt.Color(51, 51, 255));
        btnIniciarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarPanelMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INICIAR");

        javax.swing.GroupLayout btnIniciarPanelLayout = new javax.swing.GroupLayout(btnIniciarPanel);
        btnIniciarPanel.setLayout(btnIniciarPanelLayout);
        btnIniciarPanelLayout.setHorizontalGroup(
            btnIniciarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIniciarPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnIniciarPanelLayout.setVerticalGroup(
            btnIniciarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnIniciarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnRegistrarPanel.setBackground(new java.awt.Color(51, 51, 255));
        btnRegistrarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarPanelMouseExited(evt);
            }
        });
        btnRegistrarPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegistrarPanelKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTRAR");

        javax.swing.GroupLayout btnRegistrarPanelLayout = new javax.swing.GroupLayout(btnRegistrarPanel);
        btnRegistrarPanel.setLayout(btnRegistrarPanelLayout);
        btnRegistrarPanelLayout.setHorizontalGroup(
            btnRegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btnRegistrarPanelLayout.setVerticalGroup(
            btnRegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addComponent(txtIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnIniciarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(140, 140, 140))))
            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                    .addContainerGap(150, Short.MAX_VALUE)
                    .addComponent(txtGmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(114, 114, 114)))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(txtIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnIniciarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnRegistrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(txtGmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(268, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoUsuarioActionPerformed
        // TODO add your handling code here:
        combo();
        
        
        
    }//GEN-LAST:event_comboTipoUsuarioActionPerformed

    private void txtCelularestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularestudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularestudianteActionPerformed

    private void txtFacultadestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacultadestudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacultadestudianteActionPerformed

    private void txtSemestreestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemestreestudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemestreestudianteActionPerformed

    private void txtOficionbienestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOficionbienestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOficionbienestarActionPerformed

    private void txtDepartamentobienestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentobienestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentobienestarActionPerformed

    private void txtCelularbienestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularbienestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularbienestarActionPerformed

    private void txtCelularprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularprofesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularprofesorActionPerformed

    private void comboBoxGeneroProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGeneroProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxGeneroProfesorActionPerformed

    private void comoboBoxGeneroBienestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoboBoxGeneroBienestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comoboBoxGeneroBienestarActionPerformed

    private void btnIniciarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarPanelMouseClicked
        // TODO add your handling code here:
         login();
    }//GEN-LAST:event_btnIniciarPanelMouseClicked

    private void btnRegistrarPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistrarPanelKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRegistrarPanelKeyPressed

    private void btnIniciarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarPanelMouseEntered
        // TODO add your handling code here:normal=[0,0,51],5  al pasar mause=0,51,209
        Border bordeNuevo = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        btnIniciarPanel.setBorder(bordeNuevo);
        btnIniciarPanel.setBackground(new java.awt.Color(0,51,209));
        
    }//GEN-LAST:event_btnIniciarPanelMouseEntered

    private void btnRegistrarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarPanelMouseClicked
        // TODO add your handling code here:
        Registro.setVisible(true);
        Registro.setSize(269, 200);
    }//GEN-LAST:event_btnRegistrarPanelMouseClicked

    private void btnIniciarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarPanelMouseExited
        // TODO add your handling code here:
        Border dorde = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnIniciarPanel.setBorder(dorde);
        btnIniciarPanel.setBackground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_btnIniciarPanelMouseExited

    private void btnRegistrarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarPanelMouseEntered
        // TODO add your handling code here:
        Border bordeNormal = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        btnRegistrarPanel.setBorder(bordeNormal);
        btnRegistrarPanel.setBackground(new java.awt.Color(0,51,209));
               
        
    }//GEN-LAST:event_btnRegistrarPanelMouseEntered

    private void btnRegistrarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarPanelMouseExited
        // TODO add your handling code here:
        Border borde = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnRegistrarPanel.setBorder(borde);
        btnRegistrarPanel.setBackground(new java.awt.Color(51,51,255));
                
    }//GEN-LAST:event_btnRegistrarPanelMouseExited

    private void btnAtrasPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasPanelMouseClicked
        // TODO add your handling code here:
        Registro.dispose();
    }//GEN-LAST:event_btnAtrasPanelMouseClicked

    private void btnAtrasPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasPanelMouseEntered
        // TODO add your handling code here:
        Border nuevoBorte = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        btnAtrasPanel.setBackground(new java.awt.Color(0,51,209));
        btnAtrasPanel.setBorder(nuevoBorte);
    }//GEN-LAST:event_btnAtrasPanelMouseEntered

    private void btnAtrasPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasPanelMouseExited
        // TODO add your handling code here:
        Border nuevo = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnAtrasPanel.setBackground(new java.awt.Color(51,51,255));
        btnAtrasPanel.setBorder(nuevo);
    }//GEN-LAST:event_btnAtrasPanelMouseExited

    private void btnPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanel2MouseClicked
        // TODO add your handling code here:
        registrarEstudiante();
      Estudiante.dispose();
      Registro.dispose();
    }//GEN-LAST:event_btnPanel2MouseClicked

    private void btnPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanel1MouseClicked
        // TODO add your handling code here:
        Estudiante.dispose();
    }//GEN-LAST:event_btnPanel1MouseClicked

    private void btnPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanel1MouseEntered
        // TODO add your handling code here:
          Border nuevoBorte = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
           btnPanel1.setBackground(new java.awt.Color(0,51,209));
            btnPanel1.setBorder(nuevoBorte);
    }//GEN-LAST:event_btnPanel1MouseEntered

    private void btnPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanel1MouseExited
        // TODO add your handling code here:
        Border nuevo = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnPanel1.setBackground(new java.awt.Color(51,51,255));
        btnPanel1.setBorder(nuevo);
    }//GEN-LAST:event_btnPanel1MouseExited

    private void btnPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanel2MouseEntered
        // TODO add your handling code here:
        Border nuevoBorte = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        btnPanel2.setBackground(new java.awt.Color(0,51,209));
        btnPanel2.setBorder(nuevoBorte);
    }//GEN-LAST:event_btnPanel2MouseEntered

    private void btnPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanel2MouseExited
        // TODO add your handling code here:
        Border nuevo = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnPanel2.setBackground(new java.awt.Color(51,51,255));
        btnPanel2.setBorder(nuevo);
    }//GEN-LAST:event_btnPanel2MouseExited

    private void btnPanelRegistrar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelRegistrar5MouseClicked
        // TODO add your handling code here:
         registrarProfesor();

        Profesor.dispose();
        Registro.dispose();
    }//GEN-LAST:event_btnPanelRegistrar5MouseClicked

    private void btnPanelRegresar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelRegresar4MouseClicked
        // TODO add your handling code here:
        Profesor.dispose();
    }//GEN-LAST:event_btnPanelRegresar4MouseClicked

    private void btnPanelRegistrar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelRegistrar5MouseEntered
        // TODO add your handling code here:
         Border nuevoBorte = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        btnPanelRegistrar5.setBackground(new java.awt.Color(0,51,209));
        btnPanelRegistrar5.setBorder(nuevoBorte);
    }//GEN-LAST:event_btnPanelRegistrar5MouseEntered

    private void btnPanelRegistrar5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelRegistrar5MouseExited
        // TODO add your handling code here:
         Border nuevo = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnPanelRegistrar5.setBackground(new java.awt.Color(51,51,255));
        btnPanelRegistrar5.setBorder(nuevo);
    }//GEN-LAST:event_btnPanelRegistrar5MouseExited

    private void btnPanelRegresar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelRegresar4MouseEntered
        // TODO add your handling code here:
         Border nuevoBorte = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        btnPanelRegresar4.setBackground(new java.awt.Color(0,51,209));
        btnPanelRegresar4.setBorder(nuevoBorte);
    }//GEN-LAST:event_btnPanelRegresar4MouseEntered

    private void btnPanelRegresar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelRegresar4MouseExited
        // TODO add your handling code here:
         Border nuevo = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnPanelRegresar4.setBackground(new java.awt.Color(51,51,255));
        btnPanelRegresar4.setBorder(nuevo);
    }//GEN-LAST:event_btnPanelRegresar4MouseExited

    private void BTNregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNregistrarMouseClicked
        // TODO add your handling code here:
        registrarBienestar();
        BienestarDialogo.dispose();
        Registro.dispose();
    }//GEN-LAST:event_BTNregistrarMouseClicked

    private void BTNregistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNregistrarMouseEntered
        // TODO add your handling code here:
        Border nuevoBorte = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        BTNregistrar.setBackground(new java.awt.Color(0,51,209));
        BTNregistrar.setBorder(nuevoBorte);
    }//GEN-LAST:event_BTNregistrarMouseEntered

    private void BTNregistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNregistrarMouseExited
        // TODO add your handling code here:
        Border nuevo = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        BTNregistrar.setBackground(new java.awt.Color(51,51,255));
        BTNregistrar.setBorder(nuevo);
    }//GEN-LAST:event_BTNregistrarMouseExited

    private void btnREGRESARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnREGRESARMouseClicked
        // TODO add your handling code here:
        BienestarDialogo.dispose();
    }//GEN-LAST:event_btnREGRESARMouseClicked

    private void btnREGRESARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnREGRESARMouseEntered
        // TODO add your handling code here:
        Border nuevoBorte = BorderFactory.createLineBorder(new java.awt.Color(0,0,51),5);
        btnREGRESAR.setBackground(new java.awt.Color(0,51,209));
        btnREGRESAR.setBorder(nuevoBorte);
    }//GEN-LAST:event_btnREGRESARMouseEntered

    private void btnREGRESARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnREGRESARMouseExited
        // TODO add your handling code here:
        Border nuevo = BorderFactory.createLineBorder(new java.awt.Color(51,51,255),1);
        btnREGRESAR.setBackground(new java.awt.Color(51,51,255));
        btnREGRESAR.setBorder(nuevo);
    }//GEN-LAST:event_btnREGRESARMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BTNregistrar;
    private javax.swing.JDialog BienestarDialogo;
    private javax.swing.JDialog Estudiante;
    private javax.swing.JDialog Profesor;
    private javax.swing.JDialog Registro;
    private javax.swing.JPanel btnAtrasPanel;
    private javax.swing.JPanel btnIniciarPanel;
    private javax.swing.JPanel btnPanel1;
    private javax.swing.JPanel btnPanel2;
    private javax.swing.JPanel btnPanelRegistrar5;
    private javax.swing.JPanel btnPanelRegistrar6;
    private javax.swing.JPanel btnPanelRegistrar7;
    private javax.swing.JPanel btnPanelRegresar4;
    private javax.swing.JPanel btnREGRESAR;
    private javax.swing.JPanel btnRegistrarPanel;
    private javax.swing.JComboBox<String> comboBoxGeneroProfesor;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JComboBox<String> comboboxGeneroEstudiantee;
    private javax.swing.JComboBox<String> comoboBoxGeneroBienestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel login;
    private javax.swing.JTextField txtApellidobienestar;
    private javax.swing.JTextField txtApellidoestudiante;
    private javax.swing.JTextField txtApellidoprofesor;
    private javax.swing.JTextField txtCelularbienestar;
    private javax.swing.JTextField txtCelularestudiante;
    private javax.swing.JTextField txtCelularprofesor;
    private javax.swing.JTextField txtDepartamentobienestar;
    private javax.swing.JTextField txtDireccionbienestar;
    private javax.swing.JTextField txtFacultadestudiante;
    private javax.swing.JTextField txtFacultadprofesor;
    private javax.swing.JTextField txtGmailLogin;
    private javax.swing.JTextField txtGmailbienestar;
    private javax.swing.JTextField txtGmailestudiante;
    private javax.swing.JTextField txtGmailprofesor;
    private javax.swing.JTextField txtIDLogin;
    private javax.swing.JTextField txtIDbienestar;
    private javax.swing.JTextField txtIDestudiante;
    private javax.swing.JTextField txtIDprofesor;
    private javax.swing.JTextField txtNombrebienestar;
    private javax.swing.JTextField txtNombreestudiante;
    private javax.swing.JTextField txtNombreprofesor;
    private javax.swing.JTextField txtOficionbienestar;
    private javax.swing.JTextField txtProfesionprofesor;
    private javax.swing.JTextField txtProgramaestudiante;
    private javax.swing.JTextField txtProgramaprofesor;
    private javax.swing.JTextField txtSemestreestudiante;
    // End of variables declaration//GEN-END:variables

    public void combo(){
        String selecion = comboTipoUsuario.getSelectedItem().toString();
        if(selecion.equals("estudiante")){
            Estudiante.setVisible(true);
            Estudiante.setSize(560, 400);
            
            Estudiante.setLocationRelativeTo(null);
       
            
        }
        if(selecion.equals("bienestar")){
            BienestarDialogo.setVisible(true);
            BienestarDialogo.setSize(560, 400);
            BienestarDialogo.setLocationRelativeTo(null);
            
        }
        if(selecion.equals("profesor")){
            Profesor.setVisible(true);
            Profesor.setSize(560, 400);
            Profesor.setLocationRelativeTo(null);        
        }
    }
public void registrarEstudiante(){
    Estudiante estudiante = new Estudiante();
    
   
   estudiante.setId(txtIDestudiante.getText());
   estudiante.setNombre(txtNombreestudiante.getText());
   estudiante.setGmail(txtGmailestudiante.getText());
   estudiante.setApellido(txtApellidoestudiante.getText());
   estudiante.setNumeroTelefonico(txtCelularestudiante.getText());
   estudiante.setGenero(comboboxGeneroEstudiantee.getSelectedItem().toString());
   estudiante.setFacultad(txtFacultadestudiante.getText());
   estudiante.setSemestre(txtSemestreestudiante.getText());
   estudiante.setPrograma(txtProgramaestudiante.getText());
   estudiante.setTipoUsuario("ESTUDIANTE");
   
   registro.registrarEstudiante(estudiante);
}
public void registrarProfesor(){
    Profesor profesor = new Profesor();
    
    profesor.setApellido(txtApellidoprofesor.getText());
    profesor.setNombre(txtNombreprofesor.getText());
    profesor.setId(txtIDprofesor.getText());
    profesor.setGmail(txtGmailprofesor.getText());
    profesor.setNumeroTelefonico(txtCelularprofesor.getText());
    profesor.setGenero(comboBoxGeneroProfesor.getSelectedItem().toString()); // nuevo
    profesor.setTipoUsuario("PROFESOR");
    profesor.setFacultad(txtFacultadprofesor.getText());
    profesor.setProfesion(txtProfesionprofesor.getText());
    profesor.setPrograma(txtProgramaprofesor.getText());
    
    registro.registrarProfesor(profesor);
    
}
public void registrarBienestar(){
Bienestar bienestar=new Bienestar();

bienestar.setId(txtIDbienestar.getText());
bienestar.setApellido(txtApellidobienestar.getText());
bienestar.setNombre(txtNombrebienestar.getText());
bienestar.setDepartamento(txtDepartamentobienestar.getText());
bienestar.setDireccion(txtDireccionbienestar.getText());
bienestar.setGenero(comoboBoxGeneroBienestar.getSelectedItem().toString()); //nuevo
bienestar.setGmail(txtGmailbienestar.getText());
bienestar.setNumeroTelefonico(txtCelularbienestar.getText());
bienestar.setOficio(txtOficionbienestar.getText());
bienestar.setTipoUsuario("BIENESTAR");

registro.registrarBienestar(bienestar);
}
 private void login() {
        String email = txtGmailLogin.getText().trim();
        String password = txtIDLogin.getText().trim();

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese email y contraseña", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        LoginDAO loginDAO=new LoginDAO();
        Usuario usuario = loginDAO.autenticarUsuario(email, password);
        if (usuario != null) {
            JOptionPane.showMessageDialog(this, 
                "Bienvenido " + usuario.getNombre() + " " + usuario.getApellido() + 
                "\nTipo de usuario: " + usuario.getTipoUsuario(), 
                "Autenticación exitosa", JOptionPane.INFORMATION_MESSAGE);
            if (usuario.getTipoUsuario().equals("Estudiante")){
             new EstudianteProfesor().setVisible(true);
             this.dispose();
            }else if(usuario.getTipoUsuario().equals("Bienestar")){
            new BienvenidoBienestar().setVisible(true);
                         this.dispose();

            
        } else if (usuario.getTipoUsuario().equals("Profesor")){
            new ProfesorInterfas().setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, 
                "Credenciales incorrectas o usuario no existe", 
                "Error de autenticación", JOptionPane.ERROR_MESSAGE);
    }
 }
}
}




