/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Model.Evento;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elise
 */
public class ProfesorInterfas extends javax.swing.JFrame {
private static final String DIRECTORIO_EVENTO = "C:/Users/elise/OneDrive/Desktop/reservaProfesor/";
    /**
     * Creates new form Profesor
     */
    public ProfesorInterfas() {
        initComponents();
        setLocationRelativeTo(null);
        
        limpiarTabla();
        cargarEventosDesdeArchivo();
    }
       public void cargarEventosDesdeArchivo(){
        File directorio = new File(DIRECTORIO_EVENTO);
        if (!directorio.exists()){
            directorio.mkdirs();
            return;
        }
        
        File[] archivos = directorio.listFiles((dir, name) -> name.endsWith(".txt"));
        if (archivos == null) return;
        
        DefaultTableModel model = (DefaultTableModel) ModelSolicitudes1.getModel();
        model.setRowCount(0); //limpia la tabla
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        for(File archivo : archivos){
            try (BufferedReader leer = new BufferedReader(new FileReader(archivo))) {
              String line;
              String nombreEvento = "";
              String fechaInicio = "";
              String descripcion = "";
              String fechaCreada = "";
              String estado = "Pendiente";
              
              while ((line = leer.readLine()) != null) {
                if (line.startsWith("NOMBRE_EVENTO: ")) {
                    nombreEvento = line.substring("NOMBRE_EVENTO: ".length());
                    
                } else if (line.startsWith("DESCRIPCION: ")){
                    descripcion = line.substring("DESCRIPCION: ".length());
                    
                } else if (line.startsWith("FECHA_INICIO: ")) {
                    fechaInicio = line.substring("FECHA_INICIO: ".length());
                    
                } else if (line.startsWith("FECHA_CREADA: ")){
                     fechaCreada = line.substring("FECHA_CREADA".length());
                } else if (line.startsWith("ESTADO: ")) {
                    estado = line.substring("ESTADO: ".length());
                }
            }
              if(!nombreEvento.isEmpty()){
                  model.addRow(new Object[]{
                      fechaInicio,
                      nombreEvento,
                      descripcion,
                      estado,
                      //evento pendiente
                      
                      fechaCreada
                  });
              }
            } catch (IOException e){
                JOptionPane.showMessageDialog(null,"Error al leer archivo" +e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                
            }
           

        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        txtEvento = new javax.swing.JTextField();
        btnAgregarEvento = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        dateINICIO = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnAgregar1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ModelSolicitudes1 = new javax.swing.JTable();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("AGREGAR"));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCRIPCION"));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        txtEvento.setBorder(javax.swing.BorderFactory.createTitledBorder("EVENTO"));
        txtEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventoActionPerformed(evt);
            }
        });

        btnAgregarEvento.setText("AGREGAR");
        btnAgregarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEventoActionPerformed(evt);
            }
        });

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("FECHA INICIO");

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnAgregarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar))
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtEvento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(dateINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEvento)
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar.getContentPane());
        Agregar.getContentPane().setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("SISTEMA DE SOLICITUD"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        btnAgregar1.setText("AGREGAR");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("ACTUALIZAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ModelSolicitudes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FECHA DE INICIO", "EVENTO", "DESCRIPCION", "ESTADO", "CREADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ModelSolicitudes1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventoActionPerformed

    private void btnAgregarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEventoActionPerformed
     
        agregarATabla();
        agregarAArchivo();
        limpiarCampos();

        Agregar.dispose();

    }//GEN-LAST:event_btnAgregarEventoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Agregar.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        Agregar.setVisible(true);
      Agregar.setSize(400,430);
      Agregar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int selectedRow = ModelSolicitudes1.getSelectedRow();
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    //obtener el nombre del evento para eliminar el archivo
    
    String nombreEvento = ModelSolicitudes1.getValueAt(selectedRow, 1).toString();
    String nombreArchivo = DIRECTORIO_EVENTO + nombreEvento.replaceAll("[^a-zA-Z0-9]", "_")+ ".txt";
    
    //elimina archivo
    File archivo = new File(nombreArchivo);
    if(archivo.exists()) {
        archivo.delete();
    }
    
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes1.getModel();
    model.removeRow(selectedRow);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
 int selectedRow = ModelSolicitudes1.getSelectedRow();
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    // guarda el nombre del evento 
    final String nombreEventoOrigianl = ModelSolicitudes1.getValueAt(selectedRow, 1).toString();
    
    
    // Mostrar diálogo de edición con los datos actuales
    Agregar.setVisible(true);
    Agregar.setSize(365, 410);
    Agregar.setLocationRelativeTo(null);
    
    // Llenar campos con datos existentes
    txtEvento.setText(ModelSolicitudes1.getValueAt(selectedRow, 1).toString());
    txtDescripcion.setText(ModelSolicitudes1.getValueAt(selectedRow, 2).toString());
    
    // Configurar botón para actualizar en lugar de agregar
    btnAgregarEvento.setText("ACTUALIZAR");
    btnAgregarEvento.removeActionListener(btnAgregarEvento.getActionListeners()[0]);
    btnAgregarEvento.addActionListener(e -> {
        
        String nombreArchivoOriginal = DIRECTORIO_EVENTO + nombreEventoOrigianl.replaceAll("[^a-zA-Z0-9]", 
                "_")+ ".txt";
              File archivoOriginal = new File(nombreArchivoOriginal);
              if (archivoOriginal.exists()){
                  archivoOriginal.delete();
              }
        
            actualizarFila(selectedRow);
            agregarAArchivo();
            limpiarCampos();
            Agregar.dispose();
        
    });
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesorInterfas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesorInterfas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesorInterfas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesorInterfas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesorInterfas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar;
    private javax.swing.JTable ModelSolicitudes1;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregarEvento;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser dateINICIO;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
private void actualizarFila(int row) {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format(dateINICIO.getDate());
    String tomestamp = sdf.format(new Date());
    
    ModelSolicitudes1.setValueAt(fechaInicioStr, row, 0);
    ModelSolicitudes1.setValueAt(txtEvento.getText(), row, 1);
    ModelSolicitudes1.setValueAt(txtDescripcion.getText(), row, 2);
    ModelSolicitudes1.setValueAt(tomestamp, row, 4); //actualiza fecha modificacion
    
    // Restaurar botón a su estado original
    btnAgregarEvento.setText("AGREGAR");
    btnAgregarEvento.removeActionListener(btnAgregarEvento.getActionListeners()[0]);
    btnAgregarEvento.addActionListener(this::btnAgregarEventoActionPerformed);
}
public void agregarATabla() {
    Evento evento = new Evento();
    evento.setDescripcion(txtDescripcion.getText());
    evento.setFechaInicio(dateINICIO.getDate());
    evento.setNombreEvento(txtEvento.getText());
    
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format(evento.getFechaInicio());
    String timestamp = sdf.format(new Date());
    evento.setFechaCreada(timestamp);
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes1.getModel();
    model.addRow(new Object[]{
        fechaInicioStr, 
        evento.getNombreEvento(), 
        evento.getDescripcion(), 
        evento.getEstado(),
        
        timestamp
            
    });
}
private void limpiarCampos() {
    txtEvento.setText("");
    txtDescripcion.setText("");
    dateINICIO.setDate(null);
    txtNombre.setText("");
}
private void limpiarTabla() {
    DefaultTableModel model = (DefaultTableModel) ModelSolicitudes1.getModel();
    model.setRowCount(0); 
}

    private void agregarAArchivo() {
    String nombreEvento = txtEvento.getText();
    Date fechaInicio = dateINICIO.getDate();
    String descripcion = txtDescripcion.getText();
    String nombreUsuario = txtNombre.getText();
    
    if(nombreEvento.isEmpty() || fechaInicio == null || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Evento evento = new Evento();
    evento.setNombreEvento(nombreEvento);
    evento.setFechaInicio(fechaInicio);
    evento.setDescripcion(descripcion);
    evento.setNombreuUsuario(nombreUsuario);
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    evento.setFechaCreada(sdf.format(new Date()));
    
    String nombreArchivo = DIRECTORIO_EVENTO + 
                         nombreEvento.replaceAll("[^a-zA-Z0-9]", "_") + 
                         ".txt";
    
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo))) {
        writer.write("==========DATOS DEL EVENTO==========\n"); 
        writer.write("NOMBRE_EVENTO: " + evento.getNombreEvento() + "\n");
        writer.write("FECHA_INICIO: " + sdf.format(evento.getFechaInicio()) + "\n");
        writer.write("FECHA_CREADA: " + evento.getFechaCreada() + "\n");
        writer.write("DESCRIPCION: " + evento.getDescripcion() + "\n");
        writer.write("ESTADO: " + evento.getEstado()+"\n");
        writer.write("NOMBRE_USUARIO: " + evento.getNombreuUsuario());
        
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, 
            "Error al crear el archivo: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        System.err.println("Error al registrar evento: " + e.getMessage());
    }
}
}
